export enum ComputedCacheKey {
  CURRENCY_FORMAT = 'CURRENCY_FORMAT',
  PNL_CLASS = 'PNL_CLASS',
  TRADE_COUNT_FORMAT = 'TRADE_COUNT_FORMAT',
  CALENDAR_DATA = 'CALENDAR_DATA',
  EMPTY_CALENDAR = 'EMPTY_CALENDAR',
  DAY_OF_WEEK = 'DAY_OF_WEEK',
  DAYS_IN_MONTH = 'DAYS_IN_MONTH'
}
